# **Data Inconsistencies or Anomolies**

`Definition`

Data inconsistencies and anomalies refer to unexpected, incorrect, or unusual data points that deviate from the standard, expected, or correct values in a dataset. These issues can arise due to errors in data collection, entry, transmission, or integration from multiple sources. Detecting and addressing them is crucial for accurate data analysis and modeling.

Common Types of Data Inconsistencies and Anomalies

1. `Missing Values`
- **Description**: Absence of data in one or more fields where a value is expected.
- **Causes:** Data entry errors, system failures, or incomplete data collection.
- **Example**: Name: Ali Khan | **Email Address: (blank)** | Phone: 0300-1234567


2. `Duplicate Records`
- **Description:** Multiple identical or near-identical records representing the same entity.
- **Causes:** Data merging from multiple sources, repeated data entry.
- **Example**: 
    1. Row 1: Name: Sara Ahmed | ID: 101 | Email: sara@example.com
    2. Row 2: Name: Sara Ahmed | ID: 101 | Email: sara@example.com


3. `Outliers`
- **Description**: Data points significantly different from the majority of the dataset.
- **Causes:** Measurement errors, rare events, or genuine variability.
- **Example**: Name: John Doe | Age: 200

4. `Inconsistent Data Formats`
- **Description**: Variations in how data is represented (e.g., date formats, units).
- **Causes**: Data integration from different systems or manual entry.
- **Example**: 
    1. Row 1: 2025-07-10
    2. Row 2: 10/07/2025
    3. Row 3: July 10, 2025

5. `Contradictory Data`
- **Description**: Conflicting information within or across records (e.g., age and birthdate mismatch).
- **Causes**: Data entry mistakes, merging errors.
- **Example**: Name: Ayesha Malik | Birthdate: 2010-01-01 | Age: 30

6. `Invalid Values`
- **Description**: Data entries that fall outside the allowed or logical range (e.g., negative ages, impossible dates).
- **Causes**: Input errors, lack of validation checks.
- **Example**: Product: Laptop | Quantity Sold: -5

7. `Structural Anomalies`
- **Description**: Unexpected changes in the structure or schema of the data (e.g., missing columns, extra fields).
- **Causes**: System updates, schema evolution, or integration issues.
- **Example**: 
    1. Row 1: Name, Age, Email
    2. Row 2: Name, Age
    3. Row 3: Name, Age, Email, Address


8. `Noise`
- **Description**: Random errors or irrelevant data that obscure the true signal.
- **Causes**: Sensor errors, transmission issues, or background processes.
- **Example**: Temperature readings: 22, 23, **150**, 22, 23

In [1]:
# import the necessary libraries
import pandas as pd

In [5]:
# now we create a dataset on over own that contain the four colomns and contain all the things that are being discussed in the file above
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice'],
    'Age': [25, 30, 350, 40],
    'Salary': [50000, 60, 70000, 80000],
    'Gender': ['F', 'NA', 'M', 'M'],
    'Date': ['01-01-2020', '05-15-2019', '2018-07-23', '2021-03-30'],
    'Country': ['U.S.A','USA','America','United States']
}
df=pd.DataFrame(data)
df

      Name  Age  Salary Gender        Date        Country
0    Alice   25   50000      F  01-01-2020          U.S.A
1      Bob   30      60     NA  05-15-2019            USA
2  Charlie  350   70000      M  2018-07-23        America
3    Alice   40   80000      M  2021-03-30  United States

In [6]:
# first we will deal with the name colomns that has a repeating name in it
df['Name'] = df['Name'].replace('Alice', 'Alicia')
df

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  01-01-2020          U.S.A
1      Bob   30      60     NA  05-15-2019            USA
2  Charlie  350   70000      M  2018-07-23        America
3   Alicia   40   80000      M  2021-03-30  United States

In [7]:
# Next is the age colomn we we see the age of 350 years that is not possible 
df['Age']=df['Age'].replace(350,35)
df

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  01-01-2020          U.S.A
1      Bob   30      60     NA  05-15-2019            USA
2  Charlie   35   70000      M  2018-07-23        America
3   Alicia   40   80000      M  2021-03-30  United States

In [8]:
# Now in the salary colomn we see the salary of 60 per month 
df['Salary']=df['Salary'].replace(60,60000)
df

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  01-01-2020          U.S.A
1      Bob   30   60000     NA  05-15-2019            USA
2  Charlie   35   70000      M  2018-07-23        America
3   Alicia   40   80000      M  2021-03-30  United States

In [9]:
# In the Gender colomn we have so one missing value of NA value in it
df['Gender']=df['Gender'].replace('NA','M')
df

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  01-01-2020          U.S.A
1      Bob   30   60000      M  05-15-2019            USA
2  Charlie   35   70000      M  2018-07-23        America
3   Alicia   40   80000      M  2021-03-30  United States

In [12]:
# The country colomn also has some inconsistency so we will fix it too all at once
df['Country']=df['Country'].replace('USA','United States')
df['Country']=df['Country'].replace('U.S.A','United States')
df['Country']=df['Country'].replace('America','United States')
df

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  01-01-2020  United States
1      Bob   30   60000      M  05-15-2019  United States
2  Charlie   35   70000      M  2018-07-23  United States
3   Alicia   40   80000      M  2021-03-30  United States

In [13]:
# standardize Date column to ISO format (YYYY-MM-DD)
df['Date'] = pd.to_datetime(df['Date'], infer_datetime_format=True, errors='coerce')
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_6404\704233142.py:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['Date'] = pd.to_datetime(df['Date'], infer_datetime_format=True, errors='coerce')

      Name  Age  Salary Gender        Date        Country
0   Alicia   25   50000      F  2020-01-01  United States
1      Bob   30   60000      M  2019-05-15  United States
2  Charlie   35   70000      M         NaN  United States
3   Alicia   40   80000      M         NaN  United States

In [ ]:
# now we see the case of missing values in date colomns
df['Date']=df['Date'].replace('NaT','23-007-2018')
df['Date']=df['Date'].replace('')

In [2]:
# dataset of five colomns and thirty rows and contain inconsistencies or anomolies in it
data = {
    'Name': ['Alice', 'NA', 'Charlie', 'NA', 'Eve','Eve'] * 6,
    'Age': [25, 30, 35, 4000, 45,45] * 6,
    'Salary': [50000, 60000, 70000, 'NA', 90000,90000] * 6,
    'Gender': ['MALE', 'F', 'M', 'F', 'F','F'] * 6,
    'Country': ['USA', 'PAK', 'NA', 'IND', 'IRLD','IRLD'] * 6,
    'Date': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01', '2021-05-01','2021-05-01'] * 6
    }
df = pd.DataFrame(data)
df

       Name   Age Salary Gender Country        Date
0     Alice    25  50000   MALE     USA  2021-01-01
1        NA    30  60000      F     PAK  2021-02-01
2   Charlie    35  70000      M      NA  2021-03-01
3        NA  4000     NA      F     IND  2021-04-01
4       Eve    45  90000      F    IRLD  2021-05-01
5       Eve    45  90000      F    IRLD  2021-05-01
6     Alice    25  50000   MALE     USA  2021-01-01
7        NA    30  60000      F     PAK  2021-02-01
8   Charlie    35  70000      M      NA  2021-03-01
9        NA  4000     NA      F     IND  2021-04-01
10      Eve    45  90000      F    IRLD  2021-05-01
11      Eve    45  90000      F    IRLD  2021-05-01
12    Alice    25  50000   MALE     USA  2021-01-01
13       NA    30  60000      F     PAK  2021-02-01
14  Charlie    35  70000      M      NA  2021-03-01
15       NA  4000     NA      F     IND  2021-04-01
16      Eve    45  90000      F    IRLD  2021-05-01
17      Eve    45  90000      F    IRLD  2021-05-01
18    Alice    25  50000   MALE     USA  2021-01-01
19       NA    30  60000      F     PAK  2021-02-01
20  Charlie    35  70000      M      NA  2021-03-01
21       NA  4000     NA      F     IND  2021-04-01
22      Eve    45  90000      F    IRLD  2021-05-01
23      Eve    45  90000      F    IRLD  2021-05-01
24    Alice    25  50000   MALE     USA  2021-01-01
25       NA    30  60000      F     PAK  2021-02-01
26  Charlie    35  70000      M      NA  2021-03-01
27       NA  4000     NA      F     IND  2021-04-01
28      Eve    45  90000      F    IRLD  2021-05-01
29      Eve    45  90000      F    IRLD  2021-05-01
30    Alice    25  50000   MALE     USA  2021-01-01
31       NA    30  60000      F     PAK  2021-02-01
32  Charlie    35  70000      M      NA  2021-03-01
33       NA  4000     NA      F     IND  2021-04-01
34      Eve    45  90000      F    IRLD  2021-05-01
35      Eve    45  90000      F    IRLD  2021-05-01