# **Outliers in Data**
An `outlier` is a data value that is very different from most other values in a dataset. It may happen because of an error, or it may represent something unusual but real.

### **Types of Outliers**

Outliers are classified in nine types:

1. `Univariate:` Ye woh outliers hote hain jo sirf ek variable mein hote hain. For example, agar aapke data mein sirf age variable hai, to age ke outliers univariate outliers honge.
2. `Multivariate:` Ye woh outliers hote hain jo ek se zyada variables mein hote hain. For example, agar aapke data mein age aur income dono variables hain, to age aur income ke outliers multivariate outliers honge.
3. `Global:`Global outliers are data values that are extremely different from all other values in the entire dataset.They clearly stand out and are easy to notice because they are far away from the normal range of data. Examples include a runner finishing a marathon in 1.5 hours or 10 hours, while most complete it in 3–5, or a data point that is far from the main cluster of points on a scatter plot.  
4. `Local:`Local outliers are data points that are isolated from their surrounding neighbors. These outliers may not be extreme when compared to the entire dataset but are unusual within a specific local context or cluster. For instance, in a dataset of house prices, a house priced significantly higher than others in the same neighborhood would be considered a local outlier.
5. `Point:`A point outlier is a single data point that deviates significantly from the majority of other observations in a dataset. It is an individual value that is unusually high or low compared to the overall pattern of the data. For example , in a dataset of test scores where most students score between 60 and 80, a score of 150 would be considered a point outlier.
6. `Contextual:`Types of Outliers: Key to Accurate Data Analysis - AnblicksContextual outliers are data points that are considered unusual compared to their specific context, not necessarily the entire dataset. A data point might be normal in one context but an outlier in another, and identifying them requires considering factors like time, location, or other relevant conditions.For example, a temperature of 30°C might be normal in summer but an outlier in winter.
7. `Collective:`Collective outliers are groups of data points that are significantly different from the rest of the dataset when considered together, even if the individual points themselves are not outliers. These outliers often occur when data points have interrelations and the entire group deviates from the established trend. For example, in network traffic data, a sudden spike in activity from multiple sources may indicate a coordinated attack, even if each individual source's activity is not unusual on its own.
8. `Recurrent:`Recurrent outliers are extreme data points that appear multiple times or at regular intervals within a dataset, often in time-series or repeated measures data, as opposed to a single, isolated anomaly.For example, in a dataset tracking daily temperatures, if there are several days with unusually high temperatures that occur every summer, these would be considered recurrent outliers.
9. `Periodic:` unusual or extreme data points or patterns that recur at regular intervals within a time series or sequential data. Unlike typical outliers, which are isolated, one-off events, periodic outliers display a temporal regularity, appearing with a consistent frequency. For example, in a dataset tracking monthly sales, if there are spikes in sales every December due to holiday shopping, these would be considered periodic outliers.

### **Causes of Outliers**

Anything can happen due to the presence of outliers. Some common causes of outliers are as follows:

1. `Data Entry Errors`: Data ko enter karte waqt, kisi human error ki wajah se outliers ho sakte hain.
Misal ke taur par, agar aapke data mein age variable hai, aur kisi ne age ko 100 saal ki jagah 1000 saal enter kar diya, to ye ek outlier hoga.
2. `Measurement Errors`: Data ko measure karte waqt, kisi human error ki wajah se outliers ho sakte hain.
For example, agar aapke data mein height variable hai, aur kisi ne height ko 5 feet ki jagah 50 feet measure kar diya, to ye ek outlier hoga.
3. `Experimental Errors`: Data ko experiment karte waqt, kisi human error ki wajah se outliers ho sakte hain.
For example, agar aapke data mein weight variable hai, aur kisi ne weight ko 50 kg ki jagah 500 kg measure kar diya, to ye ek outlier hoga.
4. `Intentional Outliers`: Kisi ne intentionally data mein outliers add kiye hon.
For example, agar aapke data mein age variable hai, aur kisi ne age ko 100 saal ki jagah 1000 saal enter kar diya, to ye ek outlier hoga.
5. `Data Processing Errors`: Data ko process karte waqt, kisi human error ki wajah se outliers ho sakte hain.
For example, agar aapke data mein age variable hai, aur kisi ne age ko 100 saal ki jagah 1000 saal enter kar diya, to ye ek outlier hoga.
6. `Sampling Errors`: Data ko sample karte waqt, kisi human error ki wajah se outliers ho sakte hain.
For example, agar aapke data mein age variable hai, aur kisi ne age ko 100 saal ki jagah 1000 saal enter kar diya, to ye ek outlier hoga.
7. `Natural Outliers`: Data mein outliers ki wajah natural events ho sakte hain.
For example, agar aapke data mein age variable hai, aur kisi ne age ko 100 saal ki jagah 1000 saal enter kar diya, to ye ek outlier hoga.

### **Why should we care about Outliers?**

1. `Hidden Clues`: Outliers humein hidden clues dete hain. Inhe identify kar ke hum kisi hidden pattern ko discover kar sakte hain.
2. `Data Quality`: Outliers ki wajah se data quality kam ho jati hai. Inhe identify kar ke hum data quality ko improve kar sakte hain.
3. `Impact Analysis`: Outliers ki wajah se humari analysis mein error aa jata hai. Inhe identify kar ke hum analysis ko improve kar sakte hain.
4. `Better Decisions`: Outliers ki wajah se humari decisions par bhi asar padta hai. Inhe identify kar ke hum better decisions le sakte hain.
5. `Better Models`: Outliers ki wajah se humari models ki accuracy kam ho jati hai. Inhe identify kar ke hum better models bana sakte hain.
6. `Better Insights`: Outliers ki wajah se humari insights par bhi asar padta hai. Inhe identify kar ke hum better insights nikal sakte hain.
7. `Better Visualization`: Outliers ki wajah se humari visualizations ki quality kam ho jati hai. Inhe identify kar ke hum better visualizations bana sakte hain.
8. `Better Storytelling`: Outliers ki wajah se humari storytelling par bhi asar padta hai. Inhe identify kar ke hum better stories bana sakte hain.
9. `Better Data Products`: Outliers ki wajah se humari data products ki quality kam ho jati hai. Inhe identify kar ke hum better data products bana sakte hain.
10. `Better Data Science`: Outliers ki wajah se humari data science ki quality kam ho jati hai. Inhe identify kar ke hum better data science kar sakte hain.

# **Z - Score Method**

The `z-score method` is a statistical technique used to determine how far a specific data point is from the mean of a dataset, measured in terms of standard deviations. The z-score, also known as the standard score, indicates whether a value is above or below the mean and by how many standard deviations.

Z-Score ki formula ye hai:

`z = (x-mean)/sd.`
 
Where:
`Z`: is the Z-Score
`x`: is the data point
`mean`: is the mean of the data
`sd`: is the standard deviation of the data
`(x-mean)`: is the difference between the data point and the mean
`(x-mean)/sd`: is the difference between the data point and the mean in terms of standard deviations

Z-Score has following properties:
1. **Symmetry**: The Z-Score is symmetric around the mean. This means that if `x` is above the mean, then `x-mean` is positive, and if `x is below the mean, then `x-mean` is negative.
2. **Standardization**: The Z-Score standardizes the data by converting it to a common scale, which is the number of standard deviations from the mean.
3. **Interpretation**: The Z-Score can be interpreted as the number of standard deviations from the mean.
4. **Normal Distribution**: The Z-Score is used to determine the probability of a data point occurring in a normal distribution.
5. Z-Score has mean 0 aur standard deviation 1 hota.
6. Z-Score is large means, data points are away from mean.
7. Z-Score is small means, data points are towrods the mean. 
8. Z-Score is less than -3 and grater than +3, the data point is outlier.

In [1]:
# Z - Score Method for Outlier Detection and Removal

## 1. Import Libraries
import numpy as np
import pandas as pd

## 2. create a sample DataFrame of one colomn that contain age data
data = {
    'Age': [25, 30, 35, 40, 100, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95,200]
}
df = pd.DataFrame(data)
df

    Age
0    25
1    30
2    35
3    40
4   100
5    45
6    50
7    55
8    60
9    65
10   70
11   75
12   80
13   85
14   90
15   95
16  200

In [2]:
## 3. Calculate the mean and standard deviation of the 'Age' column
mean_age = df['Age'].mean()
std_age = df['Age'].std()
print("Mean Age:", mean_age)
print("Standard Deviation of Age:", std_age)

Mean Age: 70.58823529411765
Standard Deviation of Age: 40.53865257925054

In [3]:
## 4. Calculate the Z-scores for the 'Age' column, check if the throushold is not greater than 3, if it is than print there is 
# outlier in data
z_scores = (df['Age'] - mean_age) / std_age
df['Z-Score'] = z_scores
z_scores
print("Z-Scores:\n", df['Z-Score'])
print("------------------------------------------------------------")

## 5. Identify outliers based on Z-scores
outliers = df[np.abs(df['Z-Score']) > 3]
if not outliers.empty:
    print("Outliers detected:")
    print(outliers)
else:
    print("No outliers detected.")

Z-Scores:
 0    -1.124562
1    -1.001223
2    -0.877884
3    -0.754545
4     0.725524
5    -0.631206
6    -0.507867
7    -0.384528
8    -0.261189
9    -0.137850
10   -0.014510
11    0.108829
12    0.232168
13    0.355507
14    0.478846
15    0.602185
16    3.192306
Name: Z-Score, dtype: float64
------------------------------------------------------------
Outliers detected:
    Age   Z-Score
16  200  3.192306

In [4]:
## 6. Remove outliers from the DataFrame
df_no_outliers = df[np.abs(df['Z-Score']) <= 3]
df_no_outliers

    Age   Z-Score
0    25 -1.124562
1    30 -1.001223
2    35 -0.877884
3    40 -0.754545
4   100  0.725524
5    45 -0.631206
6    50 -0.507867
7    55 -0.384528
8    60 -0.261189
9    65 -0.137850
10   70 -0.014510
11   75  0.108829
12   80  0.232168
13   85  0.355507
14   90  0.478846
15   95  0.602185

In [5]:
# 1. Import libraries
import numpy as np
from scipy import stats

# 2. Sample data
data = [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 110.0]

# 3. Calculate the Z-score for each data point
z_scores = np.abs(stats.zscore(data))

# 4. Set a threshold for identifying outliers
threshold = 2.5 
outliers = np.where(z_scores > threshold)[0]

# 5. print the data
print("----------------------------------------")
print("Data:", data)
print("----------------------------------------")

print("Indices of Outliers:", outliers)
print("Outliers:", [data[i] for i in outliers])

# 6. Remove outliers
data = [data[i] for i in range(len(data)) if i not in outliers]
print("----------------------------------------")
print("Data without outliers:", data)

----------------------------------------
Data: [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 110.0]
----------------------------------------
Indices of Outliers: [9]
Outliers: [110.0]
----------------------------------------
Data without outliers: [2.5, 2.7, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0]

# **IQR (Inter Quartile Range)**

`Interquartile range (IQR)` is a measure of statistical dispersion that describes the spread of the middle 50% of values in a dataset. It is calculated as the difference between the third quartile (Q3, the 75th percentile) and the first quartile (Q1, the 25th percentile):

`IQR=Q3−Q1`

The IQR is also called the midspread, middle 50%, fourth spread, or H-spread. It is a robust measure of variability because it is not affected by extreme values or outliers, focusing only on the central portion of the data. The IQR is commonly visualized in boxplots, where it corresponds to the length of the box.

Where:
- `Q1` is the first quartile (25th percentile)
- `Q3` is the third quartile (75th percentile)
- `IQR` is the interquartile range,is the difference between the third quartile and the first quartile

IQR has following properties:

- IQR has a median of 0 and standard deviation 1.
- IQR has large value means, the data points are away from median.
- IQR has small value means, the data points are towords the median.

In [6]:
# Step 1: Import the required libraries
import pandas as pd
import numpy as np

# Step 2: Create the data
data = pd.DataFrame({'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 50]})

# Step 3: Calculate the first and third quartile
Q1 = np.percentile(data['Age'], 25, interpolation = 'midpoint')
Q3 = np.percentile(data['Age'], 75, interpolation = 'midpoint')

# Step 4: Calculate the IQR
IQR = Q3 - Q1

# Step 5: Calculate the lower and upper bound
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

# Step 6: Print the data
print("----------------------------------------")
print(f"Here is the data with outliers:\n {data}")
print("----------------------------------------")
# Step 7: Print the outliers
print(f"Here are the outliers based on the IQR threshold:\n {data[(data['Age'] < lower_bound) | (data['Age'] > upper_bound)]}")
print("----------------------------------------")
# Step 8: Remove the outliers
data = data[(data['Age'] >= lower_bound) & (data['Age'] <= upper_bound)]

# Step 9: Print the data without outliers
print(f"Here is the data without outliers:\n {data}")

----------------------------------------
Here is the data with outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30
11   50
----------------------------------------
Here are the outliers based on the IQR threshold:
     Age
11   50
----------------------------------------
Here is the data without outliers:
     Age
0    20
1    21
2    22
3    23
4    24
5    25
6    26
7    27
8    28
9    29
10   30

# **K-Means Clustering**

`K-means clustering` is an unsupervised machine learning algorithm used to partition a dataset into `K` distinct clusters based on feature similarity. The algorithm aims to group data points in such a way that points within the same cluster are more similar to each other than to those in other clusters.

`The K-means algorithm works as follows:`
1. **Initialization**: Select `K` initial centroids randomly from the dataset.
2. **Assignment Step**: Assign each data point to the nearest centroid based on a distance
    metric (commonly Euclidean distance). This forms `K` clusters.
3. **Update Step**: Recalculate the centroids of the newly formed clusters by taking the mean of all data points assigned to each cluster.
4. **Repeat**: Repeat the assignment and update steps until convergence, which occurs when the centroids no longer change significantly or a maximum number of iterations is reached. metric (commonly Euclidean distance). This forms `K` clusters.

`K-means clustering has following properties:`
- K-means clustering is sensitive to the initial placement of centroids. Different initializations can lead to different clustering results.
- K-means clustering assumes that clusters are spherical and equally sized, which may not always be the case in real-world data.
- K-means clustering is efficient and scalable, making it suitable for large datasets.
- K-means clustering can be used for outlier detection by identifying data points that are far from their assigned cluster centroids.
- K-means clustering requires the number of clusters `K` to be specified in advance, which can be challenging if the optimal number of clusters is unknown.
- K-means clustering works best with continuous numerical data and may not perform well with categorical or mixed data types.
- K-means clustering can be sensitive to the presence of outliers, which can distort the cluster centroids and affect the overall clustering results.
- K-means clustering can be evaluated using metrics such as inertia (within-cluster sum of squares) and silhouette score to assess the quality of the clustering results.
- K-means clustering can be visualized using scatter plots or other graphical representations to help interpret the clustering results.

In [7]:
# import necessary libraries
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans  

# create a sample DataFrame of one colomn that contain age data
data = {
    'Age': [25, 30, 35, 40, 100, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95,200]
}
df = pd.DataFrame(data)

# apply KMeans clustering to identify outliers

kmeans = KMeans(n_clusters=2, random_state=0).fit(df[['Age']])
df['Cluster'] = kmeans.labels_

# identify the cluster with the smaller number of points as outliers

outlier_cluster = df['Cluster'].value_counts().idxmin()
outliers = df[df['Cluster'] == outlier_cluster]
print("----------------------------------------")
print(f"Here is the data with outliers:\n {df}")
print("----------------------------------------")
print(f"Here are the outliers based on the KMeans clustering:\n {outliers}")
print("----------------------------------------")

# remove the outliers

df = df[df['Cluster'] != outlier_cluster]
print(f"Here is the data without outliers:\n {df}")

----------------------------------------
Here is the data with outliers:
     Age  Cluster
0    25        0
1    30        0
2    35        0
3    40        0
4   100        0
5    45        0
6    50        0
7    55        0
8    60        0
9    65        0
10   70        0
11   75        0
12   80        0
13   85        0
14   90        0
15   95        0
16  200        1
----------------------------------------
Here are the outliers based on the KMeans clustering:
     Age  Cluster
16  200        1
----------------------------------------
Here is the data without outliers:
     Age  Cluster
0    25        0
1    30        0
2    35        0
3    40        0
4   100        0
5    45        0
6    50        0
7    55        0
8    60        0
9    65        0
10   70        0
11   75        0
12   80        0
13   85        0
14   90        0
15   95        0

c:\ProgramData\miniconda3\envs\py_ml\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(