# Feature Encoding

# 1. One hot encoding

In [1]:
# import the necessary libary
import pandas as pd

In [3]:
# now we make the sample data of over own
df=pd.DataFrame({
    'gender':['male','female','female','male'],
    'status':['single','married','single','married']
})
df

   gender   status
0    male   single
1  female  married
2  female   single
3    male  married

In [4]:
# now do the one hot encoding on the df dataset
encoded_df=pd.get_dummies(df)
encoded_df

   gender_female  gender_male  status_married  status_single
0          False         True           False           True
1           True        False            True          False
2           True        False           False           True
3          False         True            True          False

# 2. Label encoding

In [5]:
# imprort the necessary libary for the label encoding
import sklearn.preprocessing as label_encoder

In [7]:
# take the sample data of over own
data_1=pd.DataFrame({
    'gender':['male','female','female','male'],
    'status':['single','married','single','married']
})
data_1

   gender   status
0    male   single
1  female  married
2  female   single
3    male  married

In [9]:
# now we do the label encoding on the data_1
le = label_encoder.LabelEncoder()
data_1['gender']=le.fit_transform(data_1['gender'])
data_1

   gender   status
0       1   single
1       0  married
2       0   single
3       1  married

In [10]:
# now we do the label encoding on the data_1
le = label_encoder.LabelEncoder()
data_1['status']=le.fit_transform(data_1['status'])
data_1

   gender  status
0       1       1
1       0       0
2       0       1
3       1       0

# 3. Ordinal encoding

In [11]:
# imprort the necessary libary for the label encoding
import sklearn.preprocessing as ordinal_encoder

In [13]:
# take the sample data of over own
data_2=pd.DataFrame({
    'gender':['male','female','female','male'],
    'status':['single','married','single','married']
})
data_2

   gender   status
0    male   single
1  female  married
2  female   single
3    male  married

In [14]:
# now we do the ordinal encoding on the data_1
oe=ordinal_encoder.OrdinalEncoder()
data_2['gender']=oe.fit_transform(data_2[['gender']])
data_2

   gender   status
0     1.0   single
1     0.0  married
2     0.0   single
3     1.0  married

In [15]:
# now we do the ordinal encoding on the data_1
oe=ordinal_encoder.OrdinalEncoder()
data_2['status']=oe.fit_transform(data_2[['status']])
data_2

   gender  status
0     1.0     1.0
1     0.0     0.0
2     0.0     1.0
3     1.0     0.0